### ISSUE TITLE
Milestone 3

### ISSUE THREAD

**Issue by igorsk239** [kalabhonza/PA165-music-band-manager#39]
Changes which need to be implemented 
## Backend
   - [x] implement user authentization (look at (this)[https://github.com/SedaQ/rest-training/tree/master/security/src/main/java/com/sedaq/training/security])
   - [x] how to determine user roles
   - [x] exceptions for frontend - do these on service layer  rest should not be having these -> error message, status code etc.
   - [x] password encryption  I would suggest PasswordEncoder
   - [ ] as stated in requirements  backend and frontend should run on same port therefore we need to use nginx or something else to have backend at `http://localhost:8080/pa165/rest` and frontend at `http://localhost:8080/pa165`
   - [x] figure out how to let musician accept offer
   - [x] Remove Band attribute from Manager and Musician use IDs only
   - [x] create test data -> fill database
   - [x] musician service -> method to get all musicians without band
   - [x] decline offer for musician -> rest endpoint, service, etc.
## Frontend
   - [x] Band component -> zobrazuje se místo nazvu pisnicky delka pisnicky
   - [x] Nejde mi vytvořit kapela pokud ji manager nema
   - [x] In interceptor send user from storage with every request
   - [ ] add song buttons (the content already displayed disappears)
   - [x] Duration in songs (just sample data dont work)
   - [x] Band component -> present data about band -> Tours, albums, songs, members
   - [x] Profile component -> present data about manager or musician
   - [x] Registrations formular if needed
   - [x] populate button to fill in template data for presentation
   - [x] Band service (model, api service, service, mapper, dto)
   - [x] Musician service (model, api service, service, mapper, dto)
   - [x] Manager service (model, api service, service, mapper, dto)
   - [x] Component for listing musicians and offer dialog (Manager only)
   - [x] Offers component for musician
   - [x] Manager can create band
   - [x] Manager can create album, song, tour, concert
   - [x] CORS errors
   - [ ] front end display exceptions from backend
   - [x] musician having band dont see any offers

**Comment by igorsk239** [comment]
Currently working on Offers presentation on frontend side
